# Generated by Django 4.2.6 on 2023-12-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='field2',
            new_name='apple',
        ),
        migrations.AddField(
            model_name='schedule',
            name='user',
            field=models.TextField(default='No user'),
            preserve_default=False,
        ),
    ]
