# Generated by Django 4.2.6 on 2023-12-11 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_rename_apple_schedule_jobcode_schedule_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='dateStarting',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 15, 40, 44, 448358)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2023, 12, 11, 15, 40, 44, 448373)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2023, 12, 11, 15, 40, 44, 448368)),
        ),
    ]
