# Generated by Django 4.2.6 on 2023-12-11 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_schedule_datestarting_alter_schedule_endtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='jobCode',
            new_name='Job Number',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='user',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='dateStarting',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='startTime',
        ),
        migrations.AddField(
            model_name='schedule',
            name='Date',
            field=models.DateField(default=datetime.datetime(2023, 12, 11, 15, 43, 23, 475651)),
        ),
        migrations.AddField(
            model_name='schedule',
            name='End Time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 11, 15, 43, 23, 475667)),
        ),
        migrations.AddField(
            model_name='schedule',
            name='Start Time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 11, 15, 43, 23, 475662)),
        ),
    ]
