# Generated by Django 4.2.6 on 2023-12-11 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_rename_jobcode_schedule_job_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='Job Number',
            new_name='jobCode',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='End Time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Start Time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='dateStarting',
            field=models.DateField(default=datetime.datetime(2023, 12, 11, 15, 45, 15, 907285)),
        ),
        migrations.AddField(
            model_name='schedule',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2023, 12, 11, 15, 45, 15, 907298)),
        ),
        migrations.AddField(
            model_name='schedule',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2023, 12, 11, 15, 45, 15, 907294)),
        ),
    ]
