# Generated by Django 4.2.6 on 2024-01-09 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_schedule_datestarting_alter_schedule_endtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('dateStarting', models.DateField(default=datetime.datetime(2024, 1, 9, 13, 45, 29, 655511))),
                ('startTime', models.TimeField(default=datetime.datetime(2024, 1, 9, 13, 45, 29, 655515))),
                ('endTime', models.TimeField(default=datetime.datetime(2024, 1, 9, 13, 45, 29, 655519))),
                ('jobCode', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='dateStarting',
            field=models.DateField(default=datetime.datetime(2024, 1, 9, 13, 45, 29, 655370)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2024, 1, 9, 13, 45, 29, 655384)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2024, 1, 9, 13, 45, 29, 655380)),
        ),
    ]
