# Generated by Django 4.2.6 on 2024-01-09 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_shiftmarketplace_alter_schedule_datestarting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftmarketplace',
            name='user',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='dateStarting',
            field=models.DateField(default=datetime.datetime(2024, 1, 9, 13, 49, 5, 35498)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2024, 1, 9, 13, 49, 5, 35512)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2024, 1, 9, 13, 49, 5, 35508)),
        ),
        migrations.AlterField(
            model_name='shiftmarketplace',
            name='dateStarting',
            field=models.DateField(default=datetime.datetime(2024, 1, 9, 13, 49, 5, 35632)),
        ),
        migrations.AlterField(
            model_name='shiftmarketplace',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2024, 1, 9, 13, 49, 5, 35640)),
        ),
        migrations.AlterField(
            model_name='shiftmarketplace',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2024, 1, 9, 13, 49, 5, 35636)),
        ),
    ]
