# Generated by Django 4.2.6 on 2024-01-10 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_remove_shiftmarketplace_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftmarketplace',
            name='shiftID',
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='dateStarting',
            field=models.DateField(default=datetime.datetime(2024, 1, 10, 0, 39, 32, 759441)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2024, 1, 10, 0, 39, 32, 759455)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2024, 1, 10, 0, 39, 32, 759451)),
        ),
        migrations.AlterField(
            model_name='shiftmarketplace',
            name='dateStarting',
            field=models.DateField(default=datetime.datetime(2024, 1, 10, 0, 39, 32, 759576)),
        ),
        migrations.AlterField(
            model_name='shiftmarketplace',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2024, 1, 10, 0, 39, 32, 759583)),
        ),
        migrations.AlterField(
            model_name='shiftmarketplace',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2024, 1, 10, 0, 39, 32, 759580)),
        ),
    ]
